### ISSUE TITLE
Support for .less CSS Modules

### ISSUE THREAD

**Issue by edvardsniedre** [fwouts/react-screenshot-test#139]
Is there a way to make it work with .less CSS Modules? I currently get this error.

<img width="416" alt="Screenshot 2020-02-14 at 13 31 48" src="https://user-images.githubusercontent.com/7050068/74535824-911e6680-4f2e-11ea-9383-a502fbcaf4bd.png">

**Comment by fwouts** [comment]
Hi Edvards,

At this point, .less isn't supported, and .less CSS modules aren't either.

If you're willing to give it a try, I wrote [some documentation to explain how CSS support works](https://github.com/fwouts/react-screenshot-test/blob/master/docs/supporting-css.md). You can follow the same principles to send a PR adding .less support :)

Let me know if anything is missing!

**Comment by zhaoyao91** [comment]
vote for less
