### ISSUE TITLE
Do you have to do something special to get it working with git LFS?

### ISSUE THREAD

**Issue by jeznag** [fwouts/react-screenshot-test#23]
e.g. https://github.com/fwouts/react-screenshot-test/blob/master/example/__image_snapshots__/FancyButton%20-%20Desktop%20-%20empty%20label-snap.png is using git LFS. Is there something special you have to do to push up the snapshots using LFS? File storage has always been my concern with git based screenshot storage.

**Comment by fwouts** [comment]
Hi @jeznag, I've added some more information in the README.

I didn't have to do anything apart from adding the `.gitattributes`, because GitHub supports Git LFS.

Does this answer your question? :)

**Comment by jeznag** [comment]
Thanks!

**Comment by fwouts** [comment]
Hi @jeznag, just a heads-up that if you prefer not to use Git LFS, you can now use Percy. See https://github.com/fwouts/react-screenshot-test#usage-with-percy
