### ISSUE TITLE
Jenkins CI

### ISSUE THREAD

**Issue by garmeeh** [fwouts/react-screenshot-test#239]
Hey @fwouts, more a question that an issue 😅 

Setting up a stage in our Jenkins CI and this is the output:

```
 jest -c jest.screenshot.config.js

[DEBUG:global-setup] Screenshot server setup initiated.
[DEBUG:global-setup] Creating screenshot server.
[DEBUG:global-setup] Screenshot server instance created.
[DEBUG:global-setup] Starting screenshot server.
[DEBUG:LocalScreenshotServer] start() initiated.
[DEBUG:LocalScreenshotServer] Starting renderer.
[DEBUG:PuppeteerScreenshotRenderer] start() initiated.
[DEBUG:PuppeteerScreenshotRenderer] Launching Chrome browser.
[DEBUG:PuppeteerScreenshotRenderer] Chrome browser launched.
[DEBUG:LocalScreenshotServer] Renderer started.
[DEBUG:LocalScreenshotServer] Attempting to listen on port 3038.
[DEBUG:LocalScreenshotServer] Successfully listening on port 3038.
[DEBUG:global-setup] Screenshot server started.
[DEBUG:PuppeteerScreenshotRenderer] render() invoked with (name = InfoTitle - [D] - image, title and one subheading, url = http://localhost:37627/render/3b118b25-3acf-4472-8575-66dbb6da7aaf).
```

Because there is no Docker for it available is it falling back to local mode?

**Comment by fwouts** [comment]
Yes! That's exactly what's supposed to happen, the way the library is designed. Is this what you expect?

**Comment by garmeeh** [comment]
@fwouts that makes total sense 👍 

I just wasn't too sure. I maybe expected it to fail when looking for the docker. But only realised due to the small pixel differences of the tests being run outside of the docker image.

**Comment by garmeeh** [comment]
So do I need to force Docker on Jenkins then 🤔 If I have docker running will it know it exists and use it? 

(Sorry, Docker and CI is not my strongest 😅)

**Comment by fwouts** [comment]
Sorry for the delay. Yes, that should be all you need. See [this code](https://github.com/fwouts/react-screenshot-test/blob/3482b75cf3910be7d15624c757856bc33a8133ab/src/lib/screenshot-server/config.ts#L31): if `SCREENSHOT_MODE` is not set in the environment, then it'll automatically pick Docker if present, and fall back to local rendering otherwise.
