### ISSUE TITLE
It didn't render Chinese well

### ISSUE THREAD

**Issue by zhaoyao91** [fwouts/react-screenshot-test#243]
I've create a button which has content "你好，007".

The expected effect is 

![image](https://user-images.githubusercontent.com/3808838/87877606-dd0b9500-ca11-11ea-9dd5-01d8c2b36e51.png)

But the screenshot shows as below

![image](https://user-images.githubusercontent.com/3808838/87877627-edbc0b00-ca11-11ea-9f0d-2eca01ef3350.png)

**Comment by fwouts** [comment]
Sorry for the delay, and thank you for the bug report!

I'm still trying to figure out why this happens. I suspect it's an issue with the Docker image which wouldn't include the required fonts.

**Comment by fwouts** [comment]
Could you please check out v2.1.1 and let me know if it's fixed for you? :)

**Comment by zhaoyao91** [comment]
Thanks, it works! Great project
