### ISSUE TITLE
Difficult to debug errors

### ISSUE THREAD

**Issue by bcheidemann** [fwouts/react-screenshot-test#289]
Hi,

love the project - super useful! I had an issue with running the test and getting a generic async error message. I managed to debug the error by putting the ReactScreenshotTest.create(...) inside a describe which gave me far more detailed error messages. I thought it may be worth mentioning this in the documentation as several of my co-workers have had the same issue.

Thanks!

**Comment by fwouts** [comment]
That's a great suggestion, thanks @bcheidemann. I've updated all the examples in v2.2.2 to use this approach 🎉
