### ISSUE TITLE
Delay before taking screenshots?

### ISSUE THREAD

**Issue by bcheidemann** [fwouts/react-screenshot-test#291]
Hi,

I'm having some issues taking screenshots of functional components which make use of useState and useEffect. I believe it's taking a screenshot before the component is updated by the useEffect. A feature to add a delay before taking a screenshot would be really useful for this and other cases (e.g. components with animations). Is it possible to add this?

Thanks,

Ben

**Comment by fwouts** [comment]
Hi Ben, this is unfortunately not possible as the component is strictly server-side rendered. This is a limitation from how the library is implemented (client-side rendering is much more involved). 

I'd recommend splitting your component into a purely visual one, which can be screenshot tested, and a higher-level one with useEffect/useState, which can be unit tested.

**Comment by bcheidemann** [comment]
That's a shame. Thanks anyway!
