### ISSUE TITLE
scss files with url not working

### ISSUE THREAD

**Issue by supagu** [fwouts/react-screenshot-test#292]
I'm node-sass and so I have some scss files with url's in them. Here is an example:

` background: url(../assets/strategy_header.jpg) no-repeat center center;`

Now I can include the scss file in my screenshot test as normal and its picking up the styles, but not the images:

      import React from "react";
      import { ReactScreenshotTest } from "react-screenshot-test";
      import About from "../src/About";
      import {MemoryRouter} from 'react-router-dom';
      import '../src/scss/common.scss';
      
      describe("screenshots", () => {
        ReactScreenshotTest.create("About")
          .viewport("Wide", {
            width: 2000,
            height: 2000,
          })
          .viewport("Narrow", {
            width: 1000,
            height: 2000,
          })
          .viewport("Mobile", {
            width: 375,
            height: 2000,
            deviceScaleFactor: 3,
            isMobile: true,
            hasTouch: true,
            isLandscape: false,
          })
          .shoot("simple", <MemoryRouter><About  /></MemoryRouter>)
          .run();
      });

So this test renders everything styled nicely except the images that use url(....)

I'm not sure if this is related but in my react code I need to include images like this:

require('../src/assets/home_charter_hall_case_study.jpg').default

but in my screenshot tests I need to leave off the .default

**Comment by fwouts** [comment]
Hi @supagu, sorry for the delay in responding.

There are two separate issues here:
1. Static assets aren't available inside React Screenshot Test.
2. Inconsistency in exported modules for `require()`.

You should be able to fix #1 by using the `static()` method, as shown in https://github.com/fwouts/react-screenshot-test/blob/master/src/tests/images.screenshot.tsx#L11. I'm realising now that this isn't actually documented anywhere (even I had forgotten about it). If you'd like, you're very welcome to make a PR adding some documentation!

I believe you can fix #2 by setting `esModule: false` in your `file-loader` configuration, see https://webpack.js.org/loaders/file-loader. Either that, or maybe we need to change the default for `react-screenshot-test` :)

Let me know if this helps!
