### ISSUE TITLE
Error: Please call .run()

### ISSUE THREAD

**Issue by bilix** [fwouts/react-screenshot-test#293]
Hey! I'm trying to create a simple example to test a component and I'm getting `Error: Please call .run()`

Copied almost everything from the example directory. I'm using typescript and styled-components

**Comment by fwouts** [comment]
That's unfortunate! Would you mind running with `SCREENSHOT_LOGGING_LEVEL=DEBUG` and copying the output here?

As an alternative, if you could provide a minimal example to reproduce, that would be super helpful :)

**Comment by bilix** [comment]
Hey! Thanks for your answer 🙌🏻 
This is the log:

```[DEBUG:global-setup] Screenshot server setup initiated.
[DEBUG:global-setup] Creating screenshot server.
[DEBUG:global-setup] Screenshot server instance created.
[DEBUG:global-setup] Starting screenshot server.
[DEBUG:LocalScreenshotServer] start() initiated.
[DEBUG:LocalScreenshotServer] Starting renderer.
[DEBUG:PuppeteerScreenshotRenderer] start() initiated.
[DEBUG:PuppeteerScreenshotRenderer] Launching Chrome browser.
[DEBUG:PuppeteerScreenshotRenderer] Chrome browser launched.
[DEBUG:LocalScreenshotServer] Renderer started.
[DEBUG:LocalScreenshotServer] Attempting to listen on port 3038.
[DEBUG:LocalScreenshotServer] Successfully listening on port 3038.
[DEBUG:global-setup] Screenshot server started.

throw new Error("Please call .run()");
                ^

Error: Please call .run()
    at Immediate.ReactScreenshotTest.setImmediate (/Users/me/code/snapshots/node_modules/react-screenshot-test/dist/lib/react/ReactScreenshotTest.js:40:23)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

And this is my test:
```js
import {ReactScreenshotTest} from 'react-screenshot-test'
import { ViewButton } from './App'

describe('App with button', () => {

  ReactScreenshotTest.create('Button')
    .viewport('iPhoneX', {
      width: 375,
      height: 815,
      deviceScaleFactor: 3
    })
    .shoot('button displayed correctly', <ViewButton />)
    .run();
});
```

**Comment by fwouts** [comment]
Thank you! It appears it's all working fine but somehow the callback of `setImmediate()` is being called earlier than I expected.

What version of Node are you using?

Would you be able to try commenting out the call to `setImmediate()` entirely here? https://github.com/fwouts/react-screenshot-test/blob/931feefe73b636a40f877086c2363245c8d0f00b/src/lib/react/ReactScreenshotTest.ts#L55 (you could simply comment it out inside your `node_modules` directory).

If that fixes it, we should probably just get rid of it entirely.

**Comment by bilix** [comment]
Sorry for the late response. I'm using node `10.17.0`

**Comment by fwouts** [comment]
Thanks @bilix. I wasn't able to test with `v10.17.0`, but I can confirm the library seems to work fine with `v10.23.3`. Maybe try updating Node? Otherwise it'd be super helpful if you can share the sample repository so we're running off the same code :)
