### ISSUE TITLE
Integration with CRA

### ISSUE THREAD

**Issue by happylolonly** [fwouts/react-screenshot-test#294]
Hi, I am today half of the day trying to set up your library with Create React App,  but still can't do it.

Firstly I wanted to use default CRA test, but got errors, looks like because you require `testEnvironment: 'node'`. CRA doesn't allow to change this.

Then I tried with new jest config as you have in docs, but getting infinite loading (with memory increasing)

![image](https://user-images.githubusercontent.com/18665326/108713407-3ba96c00-7529-11eb-9d42-fdf8e6f316e5.png)
![image](https://user-images.githubusercontent.com/18665326/108713604-83c88e80-7529-11eb-9117-a14935fed6f6.png)

Could you please help? Ideally would allow to use with CRA.
Thanks.

**Comment by fwouts** [comment]
Thank you for the bug report @happylolonly. I found out that an error wouldn't be logged when it occurs in a specific code path, see https://github.com/fwouts/react-screenshot-test/commit/078cd3e7737cbfccce9b116e79a0cd4d13379a8f.

Would you be able to try again with the newly released package v2.2.3 instead?

**Comment by happylolonly** [comment]
Hm, I have found that after very long time, test was finished.
So maybe issue with resolving/building.

Updated to new version, the same, long loading...

Finished test showed this, how it is working with `node` test envintoment?
![image](https://user-images.githubusercontent.com/18665326/108759791-e2a7fb00-755d-11eb-8287-eb48460c4d9e.png)

**Comment by fwouts** [comment]
That's a good question. React Screenshot Test is really designed for
server-side rendering only. Would you be able to share an example repo that
exhibits the problem?
