### ISSUE TITLE
Snapshots failing randomly sometimes

### ISSUE THREAD

**Issue by adbutterfield** [fwouts/react-screenshot-test#300]
Hi!

This is an awesome project, and I have had no issues with it until today. Just upgraded to v2.3.2 and using v1.2.2 of the docker image, and on each test run, I'm getting different components failing. 

Sorry it's not much info to go off of. Let me know if I can provide you with more details!

**Comment by fwouts** [comment]
Just a thought, could it be that you need to update the Docker image you use in CI? See https://github.com/fwouts/react-screenshot-test/blob/e5f6897643859140e8d8bb2188344b55bf2c263a/.circleci/config.yml#L5 for an example.

**Comment by adbutterfield** [comment]
Oh sorry, yeah slightly different screenshots. This was not on CI, just running multiple runs on my Mac. It took more than 10 runs before I had two in a row where all the screenshots matched. I run the tests on a pre-push hook, so it was a bit comically annoying. git push, tests fail, run the tests with -u, git commit -m "update screenshots", git push, tests fail, repeat, repeat, repeat...

I'll check to CSS for obscure properties, and run with debug logs, and report back!

**Comment by fwouts** [comment]
Thank you for filing https://github.com/fwouts/react-screenshot-test/pull/301, that helps.

For further clarification, which [screenshot mode](https://github.com/fwouts/react-screenshot-test/blob/3a0526d37a4ab5c5ae4b705db776879332f94799/src/lib/screenshot-server/config.ts#L19) do you use? It sounds like you might be using `selenium`?

**Comment by adbutterfield** [comment]
I'm not setting it explicitly, so must be the default.

**Comment by adbutterfield** [comment]
A quick update:
So if I explicitly set `SCREENSHOT_MODE=puppeteer`, I don't get any failures running 10 times in a row. 
So if I explicitly set `SCREENSHOT_MODE=docker`, I got a failure on the 8th and 10th run. 

Another thing that is strange, is that the font changed as well, which affected all of the component tests. Maybe the font-family I set wasn't rendering correctly before, and now it is (or vice versa)?

<img width="424" alt="Screen Shot 2021-05-19 at 15 19 14" src="https://user-images.githubusercontent.com/4752047/118765826-91867980-b8b6-11eb-93bd-0b23303b5c84.png">

**Comment by fwouts** [comment]
Thank you for the updates :)

It's a bit of a mystery to me how you could be using `selenium` by default without setting it explicitly somewhere!

I wonder if the font issue could be a race condition. Is the font loaded asynchronously?

**Comment by adbutterfield** [comment]
Nothing out of the ordinary with the font I think. Just have `font-family` set in the CSS.

But yeah, I guess if no one else is reporting any issues, maybe this is just a problem for me?

**Comment by adbutterfield** [comment]
Actually looking closer, in the old screenshots it has Arial (fallback font), and in the new screenshots it has Source Sans Pro (the first font in my font-family declaration).

**Comment by adbutterfield** [comment]
Closing. Tests have been running/passing consistently lately. No clear reason why...
