### ISSUE TITLE
Update postcss-modules dependency to 4.0.0

### ISSUE THREAD

**Issue by gregorybolkenstijn** [fwouts/react-screenshot-test#304]
Could you update the dependency on `postcss-modules` to 4.0.0? 
Any version below 4.0.0 has a hard dependency on `postcss` v7, which is causing an error in my build chain:

```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.0, but postcss-modules uses 7.0.35.
```

Downgrading PostCSS is not an option as other tooling relies on v8 of PostCSS.

**Comment by gregorybolkenstijn** [comment]
To give some more context, my project is using PostCSS 8.3.0 and our Next.js and Storybook applications build our CSS just fine.

If I setup and use `react-screenshot-test` as documented in the readme, and then run a screenshot test I get a vague PostCSS error message: 

`UnhandledPromiseRejectionWarning: TypeError: Invalid PostCSS Plugin found at: plugins[0]`
`at node_modules/postcss-load-config/src/plugins.js:72:15`

If I prevent `postcss-load-config/src/plugins.js` from throwing errors I get some more information: 

```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.0, but postcss-modules uses 7.0.35. Perhaps this is the source of the error below.
UnhandledPromiseRejectionWarning: Error: PostCSS plugin postcss-import requires PostCSS 8.
```

I can force the `react-screenshot-test` PostCSS dependencies to use newer versions in my package.json:
```
"resolutions": {
  "react-screenshot-test/postcss-modules": "4.0.0",
  "react-screenshot-test/postcss-load-config": "3.0.1"
},
```

Running my screenshot test now works, but everything in the screenshot is unstyled. It seems to be compiling the CSS as it takes some time for this, but no styling gets added. 

Any ideas on how to solve this?

**Comment by fwouts** [comment]
Hi @gregorybolkenstijn, thanks for all the details. That sounds like a possible bug. Would you be willing to try making a PR and upgrading PostCSS?

**Comment by fwouts** [comment]
@gregorybolkenstijn sorry for the delay, I'm looking into this now. As a first step, have you tried copy-pasting the `css-modules-transform` into the `css-transform` directory, and removing anything that's specific to CSS modules?

**Comment by gregorybolkenstijn** [comment]
I tried that, but not sure if I removed everything correctly that's specific to CSS modules. It seems it has trouble parsing the output of a large global CSS file which is generated with Tailwind CSS:

![image](https://user-images.githubusercontent.com/683497/120667240-9722b880-c48d-11eb-9343-e7641783c353.png)

I'm doing this:

```
try {
  const parsed = JSON.parse(result.stdout.toString());
  css = parsed.css
} catch (e) {
  console.log(result.stdout.toString());
  console.log('e', e)
  return `
    module.exports = {};
  `;
}
```

I think the `result.stdout` or `result.stdout.toString` has a limitation which makes `JSON.parse` fail every time. If I reduce my global CSS import to a minimum, it works and renders a screenshot with some minimal styling. 

Here's the full file for `node_modules/react-screenshot-test/css-transform/index.js`:

```
// Note: this was forked from
// https://github.com/dferber90/jest-transform-css/blob/master/index.js

// Note: you must increment this version whenever you update this script or
// anything that it uses.
const TRANSFORM_VERSION = "1";

const crypto = require("crypto");
const crossSpawn = require("cross-spawn");

module.exports = {
  getCacheKey: (fileData, filename, configString, { instrument }) => {
    return (
      crypto
        .createHash("md5")
        .update(TRANSFORM_VERSION)
        .update("\0", "utf8")
        .update(fileData)
        .update("\0", "utf8")
        .update(filename)
        .update("\0", "utf8")
        .update(configString)
        // TODO load postcssrc (the config) sync and make it part of the cache
        // key
        // .update("\0", "utf8")
        // .update(getPostCssConfig(filename))
        .update("\0", "utf8")
        .update(instrument ? "instrument" : "")
        .digest("hex")
    );
  },

  process: (src, filename) => {
    // The "process" function of this Jest transform must be sync,
    // but postcss is async. So we spawn a sync process to do an sync
    // transformation!
    // https://twitter.com/kentcdodds/status/1043194634338324480
    const postcssRunner = `${__dirname}/postcss-runner.js`;
    const result = crossSpawn.sync("node", [
      "-e",
      `
        require("${postcssRunner}")(
          ${JSON.stringify({
        src,
        filename
        // config,
        // options
      })}
        )
        .then(out => { console.log(JSON.stringify(out)) })
      `
    ]);

    // check for errors of postcss-runner.js
    const error = result.stderr.toString();
    if (error) {
      throw error;
    }

    // read results of postcss-runner.js from stdout
    let css;
    let tokens;
    try {
      const parsed = JSON.parse(result.stdout.toString());
      css = parsed.css
    } catch (e) {
      console.log(result.stdout.toString());
      console.log('e', e)
      return `
        module.exports = {};
      `;
    }

    // Finally, inject the styles to the document
    return `
      const { recordCss } = require("react-screenshot-test");
      recordCss(${JSON.stringify(css)});
      module.exports = {};
    `;
  }
};
```

**Comment by fwouts** [comment]
@gregorybolkenstijn Thanks for investigating. I think you're right that there's a buffer limit size or something. I'll try to find a way to get rid of this hack altogether, hopefully it's possible now! Give me a couple of days.

**Comment by fwouts** [comment]
OK, it looks like we still need that hack. I tried another package called `deasync` and that just hangs forever (it appears to be a known issue).

Would you mind trying explicitly increasing the `maxBuffer` size by adding a third argument to `crossSpawn.sync()`? See https://stackoverflow.com/a/23429654/911298 for reference.

Try:
```ts
    const result = crossSpawn.sync("node", [ ... ], { maxBuffer: 1024 * 1024 /* 1MB */ );
```

**Comment by gregorybolkenstijn** [comment]
I don't have time to look into this at the moment, please leave this issue open and I'll get back to it quite soon.

**Comment by gregorybolkenstijn** [comment]
I'll be looking at this again next week! :)

**Comment by fwouts** [comment]
Wonderful! By the way, in the meantime I created a more general screenshot tool called [Viteshot](https://github.com/zenclabs/viteshot). I haven't yet tested it with PostCSS, but it probably works out of the box because it's based on Vite 😬

**Comment by gregorybolkenstijn** [comment]
We eventually chose to solve making screenshots with a homegrown setup, thanks for the assistance though!
