### ISSUE TITLE
Support react 17

### ISSUE THREAD

**Issue by tjoskar** [fwouts/react-screenshot-test#305]
Hi,

Is there a reason why only react 16 is supported (and not 17)?

https://github.com/fwouts/react-screenshot-test/blob/e5f6897643859140e8d8bb2188344b55bf2c263a/package.json#L81-L84

And why an only version of `jest-image-snapshot` is used that does not support the latest version of jest.

I can create a PR if you want.

Thanks,

**Comment by fwouts** [comment]
No specific reason, I simply wasn't familiar with peer dependencies versioning back when I wrote this code 🙂 Please send a PR!
