### ISSUE TITLE
Possible problem with Docker on Windows

### ISSUE THREAD

**Issue by cle-skov-dk** [fwouts/react-screenshot-test#34]
Hi there!

This library is just what we are looking for but running:
```jest -c ./configs/jest/jest.screenshot.config.js -u```

gives us the following error

![image](https://user-images.githubusercontent.com/49151515/70705164-cc54ad00-1cd3-11ea-8576-3ff8ea2a27d2.png)

Is there any way we can solve this or get more information?

the --debug and --verbose flags from jest doesn't add more output.

Thanks!

**Comment by fwouts** [comment]
Thanks for the bug report! I must admit I had forgotten that Windows existed :)

It looks like the solution is in https://github.com/apocas/dockerode/issues/290. We need to change https://github.com/fwouts/react-screenshot-test/blob/master/src/lib/screenshot-server/DockerizedScreenshotServer.ts#L17.

I'll try and take a closer look in the next day or two, but feel free to send a PR if you're feeling adventurous!

**Comment by fwouts** [comment]
Hi Christian,

This should now be fixed in v1.2.1.

One hiccup I found is that CSS Modules don't work on Windows (I filed https://github.com/fwouts/react-screenshot-test/issues/36 separately to investigate) but everything else seems to be fine.

Cheers,

- François

**Comment by cle-skov-dk** [comment]
Hi François,

That seemed to do the trick! Thanks :)

**Comment by tiagoporto** [comment]
Hi @fwouts, nice lib thanks.

This issue is happen again.

I'm using react-screenshot-test `2.3.3,` on macOS `10.15.7`.

```js
// jest.screenshot.config.js
module.exports = {
  testEnvironment: 'node',
  globalSetup: 'react-screenshot-test/global-setup',
  globalTeardown: 'react-screenshot-test/global-teardown',
  testMatch: ['**/?(*.)+(screenshot).[jt]s?(x)'],
  transform: {
    '^.+\\.[t|j]sx?$': 'babel-jest',
    '^.+\\.module\\.css$': 'react-screenshot-test/css-modules-transform',
    '^.+\\.css$': 'react-screenshot-test/css-transform',
    '^.+\\.scss$': 'react-screenshot-test/sass-transform',
    '^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      'react-screenshot-test/asset-transform',
  },
  transformIgnorePatterns: ['node_modules/.+\\.js'],
}
```

<img width="579" alt="Screen Shot 2021-11-22 at 2 43 53 PM" src="https://user-images.githubusercontent.com/3688905/142909725-846ee64a-95fd-474d-b89d-abc6af878523.png">

**Comment by fwouts** [comment]
@tiagoporto what version of Docker are you running?

**Comment by tiagoporto** [comment]
@fwouts 

<img width="349" alt="Screen Shot 2021-11-22 at 4 47 43 PM" src="https://user-images.githubusercontent.com/3688905/142925445-5647ff41-a526-459f-ac0c-3bd0ec046cf2.png">

**Comment by fwouts** [comment]
Thanks @tiagoporto. It looks like the Docker socket isn't at the usual path /var/run/docker.sock path, which is a bit weird. Have you configured it to a different path perhaps?

If you're looking for a more up-to-date alternative, you may be interested in trying out viteshot.com, which doesn't depend so heavily on Docker.

PRs welcome too 🙂

**Comment by tiagoporto** [comment]
Hi @fwouts 
> Have you configured it to a different path perhaps?
I haven't changed any config.
