### ISSUE TITLE
Is it possible to inject external stylesheets?

### ISSUE THREAD

**Issue by tpetrina** [fwouts/react-screenshot-test#35]
I am using external stylesheets which are placed in `index.html` file in my CRA setup. However, `react-screenshot-test` doesn't pick them up and I cannot get correct fonts for example.

Is it possible to inject external resources in some kind of global setup?

**Comment by fwouts** [comment]
Hi Toni,

This wasn't possible in 1.2.0, but it was an easy addition.

Please try out v1.3.0 and let me know how this works for you.

See https://github.com/fwouts/react-screenshot-test/blob/master/src/tests/remote-stylesheet.screenshot.tsx for an example :)

**Comment by tpetrina** [comment]
I will, thanks!

**Comment by tpetrina** [comment]
That was a brand fresh update! Do you know why desktop snap would have all texts missing while the mobile one works without flaws?
![LoginPage - Desktop - LoginPage-snap](https://user-images.githubusercontent.com/1407815/70861421-ec7fa880-1f2d-11ea-8725-0281e8017e38.png)

I narrowed it down to the Google Roboto font - if removed, both work, but font is missing. If added, desktop one breaks, but phone one works flawlessly.

```
.remoteStylesheet(
    'https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700'
  )
```

**Comment by fwouts** [comment]
That's intriguing!

Would you mind trying loading all font weights (remove everything after `:` in the Roboto CSS URL)?

It might be that Puppeteer doesn't wait for the font to be loaded before taking the screenshot, but I would find that surprising.

Would be helpful if you have a minimal code sample that showcases the issue 🙂

**Comment by tpetrina** [comment]
Sure, let me work on minimum repro and I'll create a new issue.
