### ISSUE TITLE
Possible problem when importing both .SCSS and .CSS

### ISSUE THREAD

**Issue by cle-skov-dk** [fwouts/react-screenshot-test#38]
Hi again!
When importing a .SCSS file which imports both a .SCSS and a .CSS file I get the following error:
![image](https://user-images.githubusercontent.com/49151515/70983597-4a8cc700-20b9-11ea-90a5-58a0d14a4a96.png)

**Comment by fwouts** [comment]
Hey Christian,

Out of curiosity would you mind trying changing your Jest config to also use the sass-transform for .CSS files?

**Comment by cle-skov-dk** [comment]
Hi again!

My jest config looks like the following:
```javascript
module.exports = {
  roots: [
    "../../src",
  ],
  testEnvironment: "node",
  globalSetup: "react-screenshot-test/global-setup",
  globalTeardown: "react-screenshot-test/global-teardown",
  testMatch: ["**/?(*.)+(screenshot).[jt]s?(x)"],
  transform: {
    "^.+\\.[t|j]sx?$": "ts-jest",
    "^.+\\.css$": "react-screenshot-test/css-transform",
    "^.+\\.scss$": "react-screenshot-test/sass-transform",
    "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "react-screenshot-test/asset-transform"
  }
};
```

**Comment by fwouts** [comment]
What I was suggesting was changing it to:
```
module.exports = {
  roots: [
    "../../src",
  ],
  testEnvironment: "node",
  globalSetup: "react-screenshot-test/global-setup",
  globalTeardown: "react-screenshot-test/global-teardown",
  testMatch: ["**/?(*.)+(screenshot).[jt]s?(x)"],
  transform: {
    "^.+\\.[t|j]sx?$": "ts-jest",
    "^.+\\.s?css$": "react-screenshot-test/sass-transform",
    "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "react-screenshot-test/asset-transform"
  }
};
```

This would ensure that both CSS and SCSS files are processed by Sass.

However, looking at your screenshot, I think the issue might actually be that you're importing a CSS file from an NPM package (normalize.css).

I was able to reproduce the issue (same stack trace as you have) by adding `import "normalize.css";` to a screenshot test. I'll look into how we can support that.

**Comment by fwouts** [comment]
OK! I think all you need is actually to add the following to your Jest config:

```js
transformIgnorePatterns: ["node_modules/.+\\.js"]
```

**Comment by leicht-io** [comment]
That did the trick ;)

**Comment by fwouts** [comment]
Woo-hoo!
