### ISSUE TITLE
Inject props. directly to createElement for <html />

### ISSUE THREAD

**Issue by leicht-io** [fwouts/react-screenshot-test#79]
Hi again @fwouts,

Just for the record, we're very happy with the work you've been doing on this library and thanks for helping to solve the various problems we've had. :) 

Yet another problem arises when we're using this library. See, we are testing an in-house component library like React Material and thus need to supply the ```<html />``` tag with a theme and a layout attribute:
```html
<html data-theme="dark" data-layout="dense">
...
</html>
```
These attributes let us the set theme-specific CSS; without them, the theme simply won't work. 
This is usually done by the app which implements the component library but since your library works differently and there's no interface to handle this, it is simply not possible. 
I can get it to work by adding the attributes as props. in line 103 in ReactComponentServer.ts:
```typescript
  private renderWithoutStyledComponents(res: Response, node: NodeDescription) {
    const html = ReactDOMServer.renderToString(
      React.createElement(
        "html",
        {"data-theme": "dark", "data-layout": "dense"}, // <----- LINE 103
        React.createElement(
          "head",
          null,
          viewportMeta,
          ...node.remoteStylesheetUrls.map(url =>
            React.createElement("link", {
              rel: "stylesheet",
              href: url
            })
          ),
          React.createElement("style", null, readRecordedCss())
        ),
        React.createElement("body", null, node.reactNode)
      )
    );

    res.send(html.split("&quot;").join("\"").split("&#x27;").join("'"));
  }
```
But this, of course, is not the right way to do it. Do you have any idea on how to solve this, or if it's even possible?

**Comment by fwouts** [comment]
I could be convinced of making props of `<html>` customisable, but I'm a bit surprised that the library you're using depends on this.

For example `@material-ui/core` seems to let you specify a ThemeProvider, which you could wrap your components within in screenshot tests.

Could you point me to the relevant documentation?
