### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by leicht-io** [fwouts/react-screenshot-test#80]
In one of our components we check if the document contains the **onpointerdown** event:
```typescript
if ('onpointerdown' in document) {

} else {

}
```

Running the tests throws the following exception:
 ```bash
 FAIL  src/components/UIButtonRound/UIButtonRound.screenshot.tsx (9.733s)
    ReferenceError: document is not defined

    > 47 |   if ('onpointerdown' in document) {
         |                          ^
      48 |     return (
      49 |       <button
      50 |         id={ props.id }

      at Object.<anonymous>.exports.UIButtonRound (../../src/components/UIButtonRound/UIButtonRound.tsx:47:26)
      at processChild (../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3206:14)
      at resolve (../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3126:5)
      at ReactDOMServerRenderer.render (../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3600:22)
      at ReactDOMServerRenderer.read (../../node_modules/react-dom/cjs/react-dom-server.node.development.js:3538:29)
      at Object.renderToString (../../node_modules/react-dom/cjs/react-dom-server.node.development.js:4247:27)
      at ReactComponentServer.renderWithoutStyledComponents (../../node_modules/react-screenshot-test/dist/lib/react/ReactComponentServer.js:76:39)
      at ../../node_modules/react-screenshot-test/dist/lib/react/ReactComponentServer.js:49:22

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        10.35s
Ran all test suites.

Process finished with exit code 1
```
This is going to be a problem in a lot of our components since we're depending on the document to be available. As far as I can read this is due to the document not being available in Node. 

A possible fix could be the following ```evaluate()```-method from the Puppeteer API (https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pageevaluatepagefunction-args) which can be used as follows (https://stackoverflow.com/questions/55702626/why-i-got-document-is-not-defined-error-in-puppeteer):
```javascript
async function gallery(page) {
   await page.waitFor(3000);
   await page.evaluate(() => {
      document.querySelector('div.image').click();
   })
}
```
... but I am not sure if the above actually solve this error but it might be worth looking into. 
Otherwise, another possible way to fix it could be by JSDOM to inject a DOM.

This might not be a problem using webdriverio and Selenium but we'll have to wait and see :)

**Comment by fwouts** [comment]
This is a tricky one. The current implementation relies entirely on server-side rendering, i.e. invoking `ReactDOMServer.renderToString()` within an Express server. Within this context, `window` and `document` simply do not exist.

The generated HTML is not interactive (there is no client-side rendering at all) so, unfortunately, the possible fix above will not work.

It may be worth clarifying in our documentation that only components that can be rendered server-side are supported. In your case, it could be as simple as changing your components to be `if (document && 'onpointerdown' in document)`.

Otherwise, supporting this would require rethinking the entire library from the ground up. The approach adopted by https://github.com/reg-viz/storycap would actually work better.

**Comment by cle-skov-dk** [comment]
Hi again :)

FIY: I managed to implement this by using JSDOM and React render() method in the renderWithoutStyledComponents() function:
```typescript
private renderWithoutStyledComponents(node: NodeDescription) {
      ...
        const dom = new JSDOM(`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">${cssCopy}</head><body><div id='app'></div></body></html>`, {
            runScripts: "dangerously",
            resources: "usable"
        });

        render(React.createElement("div", null, node.reactNode), dom.window.document.getElementById("app"));

        return dom.window.document.getElementsByTagName("html")[0].outerHTML;
    }
```

If this isn't a part of the scope of this library you may close this issue.

**Comment by fwouts** [comment]
Sorry for the delay! That's a pretty creative way to fix it. I'll play around with it and see if it makes sense to replace the current implementation with this :)

I'll keep this ticket open until that's done.

**Comment by fwouts** [comment]
I couldn't get this to work, in particular because I experienced the error "window is not defined". This seems to be because `testEnvironment` needs to be set to `jsdom`, but that would cause other issues. Abandoning until someone else runs into a similar issue.
